apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: be
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: be
    spec:
      containers:
      - image: scgskku/ask-be
        imagePullPolicy: Always
        name: be
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: ask-secret-be